import axios from 'axios';

const basePrompt = `You are an expert quiz generator. Return valid JSON only with this structure:
{
  "questions": [
    {
      "question": "string",
      "options": ["string", "string", "string", "string"],
      "correctAnswer": "string",
      "explanation": "string"
    }
  ]
}
Rules:
- Create questions about the given topic.
- Keep difficulty aligned with the requested level.
- Include exactly 4 options per question.
- Ensure only one answer is correct.
- Use plain English.
- Do not include markdown or code fences.`;

function buildFallbackQuestions(topic, difficulty, count) {
  const topics = [
    'Basic concepts',
    'Practical examples',
    'Real-world applications',
    'Common mistakes',
    'Core theory',
  ];

  const questions = Array.from({ length: Number(count) || 5 }, (_, index) => {
    const topicLabel = topics[index % topics.length];
    const safeTopic = topic || 'Technology';
    const level = difficulty || 'Medium';

    return {
      question: `Which statement best describes ${safeTopic} in ${level.toLowerCase()} level ${topicLabel}?`,
      options: [
        `It focuses on core principles and practical understanding of ${safeTopic}.`,
        `It only uses random examples without any structure.`,
        `It ignores real-world context completely.`,
        `It is useful only for advanced research and nothing else.`,
      ],
      correctAnswer: `It focuses on core principles and practical understanding of ${safeTopic}.`,
      explanation: `This answer reflects the main concept behind ${safeTopic}: learning the foundational ideas and applying them in meaningful ways.`,
    };
  });

  return { questions };
}

export default async function handler(req, res) {
  // Enable CORS
  res.setHeader('Access-Control-Allow-Credentials', 'true');
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET,OPTIONS,PATCH,DELETE,POST,PUT');
  res.setHeader(
    'Access-Control-Allow-Headers',
    'X-CSRF-Token, X-Requested-With, Accept, Accept-Version, Content-Length, Content-MD5, Content-Type, Date, X-Api-Version'
  );

  if (req.method === 'OPTIONS') {
    res.status(200).end();
    return;
  }

  if (req.method !== 'POST') {
    res.status(405).json({ error: 'Method not allowed' });
    return;
  }

  try {
    const { topic = 'Artificial Intelligence', difficulty = 'Medium', count = 5 } = req.body || {};

    const apiKey = process.env.OPENROUTER_API_KEY || process.env.OPENAI_API_KEY;

    if (!apiKey) {
      const fallback = buildFallbackQuestions(topic, difficulty, count);
      res.status(200).json(fallback);
      return;
    }

    const response = await axios.post(
      'https://openrouter.ai/api/v1/chat/completions',
      {
        model: 'openai/gpt-4o-mini',
        messages: [
          {
            role: 'system',
            content: basePrompt,
          },
          {
            role: 'user',
            content: `Generate ${count} ${difficulty} difficulty multiple-choice questions on ${topic}.`,
          },
        ],
        temperature: 0.7,
      },
      {
        headers: {
          Authorization: `Bearer ${apiKey}`,
          'Content-Type': 'application/json',
        },
      },
    );

    let payload = response.data?.choices?.[0]?.message?.content || '{}';
    payload = payload.replace(/```json|```/g, '').trim();
    const parsed = JSON.parse(payload);

    if (!parsed.questions || !Array.isArray(parsed.questions) || parsed.questions.length === 0) {
      throw new Error('No questions generated by AI');
    }

    res.status(200).json({ questions: parsed.questions.slice(0, Number(count) || 5) });
  } catch (error) {
    console.error('Quiz generation error:', error.message);

    const { topic = 'Artificial Intelligence', difficulty = 'Medium', count = 5 } = req.body || {};
    const fallback = buildFallbackQuestions(topic, difficulty, count);
    res.status(200).json(fallback);
  }
}
